### ISSUE TITLE
Fix Issue with Odom Code

### ISSUE THREAD

**Issue by guitar24t** [frcteam195/hmi_agent_2023_node#1]
https://github.com/frcteam195/hmi_agent_2023_node/blob/ceec887ebc576d6c252f059a2e3a392be7587a58/src/hmi_agent_node/main.py#L216

Issue described here appears to be occurring: https://github.com/ros/geometry/issues/109

**Comment by michaelgtodd** [comment]
@BonomiC - this is the thing you use to reset the pose right?

I'd still like to see it switched to the set pose service request instead

**Comment by michaelgtodd** [comment]
Had the wrong line.

**Comment by michaelgtodd** [comment]
@Monjhall and the kids just wrote this today

**Comment by Monjhall** [comment]
It worked in our local launch.

**Comment by michaelgtodd** [comment]
@Monjhall - I can't see how that's possible unless you changed it after you tested.
```
(_, _, yaw) = euler_from_quaternion (odometry_msg.pose.pose.orientation)
```
This unpack syntax isn't supported by the ros object, and throws an exception

However, I implemented a new structure for the geometry library (that has alot more work to be done still) to allow some new constructors, so this is fixed now in: https://github.com/frcteam195/hmi_agent_2023_node/commit/1f45ce262dc5b8ff6a73d25564b67fea3dca631a

The new code is a bit simpler:

```
    if odometry_subscriber.get() is not None:
        odometry_msg = odometry_subscriber.get()
        rotation = Rotation(odometry_msg.pose.pose.orientation)
        yaw = rotation.yaw
        yaw = normalize_to_2_pi(yaw)
        recent_heading = math.degrees(yaw)
```

Unfortunately navigating the ros msg (getting to .pose.pose.orientation) is still a bit cumbersome, especially since it doesn't seem to support autocomplete - but at least you don't have to explain quaternions to anyone 😃

**Comment by Monjhall** [comment]
This format was taken from a ROS forum post. When running local it may have worked because joystick_callback was never called? However, in that case IDK why it would've err'd for you guys. Either way, thank you, it greatly simplifies the process of getting the robot heading.

**Comment by Monjhall** [comment]
For reference:

https://www.theconstructsim.com/ros-qa-how-to-convert-quaternions-to-euler-angles/

**Comment by michaelgtodd** [comment]
@Monjhall on a rare occasion I've seen the 'keyboard' interface not actually be bound to js0 - like end up as js1 😱 - and then there'd be no joystick callbacks running

**Comment by michaelgtodd** [comment]
> For reference:
> 
> https://www.theconstructsim.com/ros-qa-how-to-convert-quaternions-to-euler-angles/

This is a little different:
```
orientation_list = [orientation_q.x, orientation_q.y, orientation_q.z, orientation_q.w]
    (roll, pitch, yaw) = euler_from_quaternion (orientation_list)
```
In their sample, orientation_list is a real python list, but in our code it's a geometry_msgs.msg._Quaternion.Quaternion - which is orientation_q in their example, and can't be unpacked like that

**Comment by michaelgtodd** [comment]
> > For reference:
> > https://www.theconstructsim.com/ros-qa-how-to-convert-quaternions-to-euler-angles/
> 
> This is a little different:
> 
> ```
> orientation_list = [orientation_q.x, orientation_q.y, orientation_q.z, orientation_q.w]
>     (roll, pitch, yaw) = euler_from_quaternion (orientation_list)
> ```
> 
> In their sample, orientation_list is a real python list, but in our code it's a geometry_msgs.msg._Quaternion.Quaternion - which is orientation_q in their example, and can't be unpacked like that

Looking at it more closely- that's really the core problem, he converted it into a list before sending to the TF function, which my new library does as well, but you were passing the ros msg straight in

**Comment by Monjhall** [comment]
Woops. That's on me. Looking stuff up on the fly is not my strong suit.
